export interface Country {
  title: string;
  value: string;
}

export interface Countries extends Array<Country> {}

export var COUNTRIES: Country[] = [
  { title: "Aruba", value: "ABW" },
  { title: "Afghanistan", value: "AFG" },
  { title: "Angola", value: "AGO" },
  { title: "Anguilla", value: "AIA" },
  { title: "Albania", value: "ALB" },
  { title: "Czech Republic", value: "CZE" },
  { title: "the Federal Republic of Germany", value: "DEU" },
  { title: "Andorra", value: "AND" },
  { title: "United Arab Emirates", value: "ARE" },
  { title: "the Argentine Republic", value: "ARG" },
  { title: "The Republic of Armenia", value: "ARM" },
  { title: "American Samoa", value: "ASM" },
  { title: "Antarctica", value: "ATA" },
  { title: "Indonesia", value: "IDN" },
  { title: "Antigua and Barbuda", value: "ATG" },
  { title: "Australia", value: "AUS" },
  { title: "Austria", value: "AUT" },
  { title: "Azerbaijan", value: "AZE" },
  { title: "Burundi", value: "BDI" },
  { title: "Belgium", value: "BEL" },
  { title: "Saint Barthelemy", value: "BLM" },
  { title: "The Republic of Benin", value: "BEN" },
  { title: "Bonaire, Sint Eustatius, and Saba", value: "BES" },
  { title: "Burkina Faso", value: "BFA" },
  { title: "Bangledesh", value: "BGD" },
  { title: "the Republic of Bulgaria", value: "BGR" },
  { title: "Bahrain", value: "BHR" },
  { title: "Commonwealth of The Bahamas", value: "BHS" },
  { title: "Bosnia and Herzegovina", value: "BIH" },
  { title: "Belarus", value: "BLR" },
  { title: "Belize", value: "BLZ" },
  { title: "Bermuda", value: "BMU" },
  { title: "Bolivia (Plurinational State *", value: "BOL" },
  { title: "Brazil", value: "BRA" },
  { title: "Barbados", value: "BRB" },
  { title: "Nation of Brunei, the Abode of Peace", value: "BRN" },
  { title: "Bhutan", value: "BTN" },
  { title: "Botswana", value: "BWA" },
  { title: "the Central African Republic", value: "CAF" },
  { title: "Canada", value: "CAN" },
  { title: "The Swiss Confederation", value: "CHE" },
  { title: "Republic of Chile", value: "CHL" },
  { title: "China", value: "CHN" },
  { title: "C\u00f4te d\u2019Ivoire", value: "CIV" },
  { title: "the Republic of Cameroon", value: "CMR" },
  { title: "Democratic Republic of the Congo", value: "COD" },
  { title: "Congo", value: "COG" },
  { title: "Cook Islands", value: "COK" },
  { title: "Colombia", value: "COL" },
  { title: "Comoros", value: "COM" },
  { title: "Cabo Verde", value: "CPV" },
  { title: "Costa Rica", value: "CRI" },
  { title: "Cuba", value: "CUB" },
  { title: "Curacao", value: "CUW" },
  { title: "Cayman Islands", value: "CYM" },
  { title: "Cyprus", value: "CYP" },
  { title: "The Repubic of Djibouti", value: "DJI" },
  { title: "the Commonwealth of Dominica", value: "DMA" },
  { title: "Denmark", value: "DNK" },
  { title: "Dominican Republic", value: "DOM" },
  { title: "Algeria", value: "DZA" },
  { title: "Ecuador", value: "ECU" },
  { title: "Egypt", value: "EGY" },
  { title: "Eritrea", value: "ERI" },
  { title: "Spain", value: "ESP" },
  { title: "Estonia", value: "EST" },
  { title: "Ethiopia", value: "ETH" },
  { title: "Finland", value: "FIN" },
  { title: "Fiji", value: "FJI" },
  { title: "Falkland Islands", value: "FLK" },
  { title: "France", value: "FRA" },
  { title: "Faroe Islands", value: "FRO" },
  { title: "Federated States of Micronesia", value: "FSM" },
  { title: "Gabon", value: "GAB" },
  { title: "United Kingdom", value: "GBR" },
  { title: "Georgia", value: "GEO" },
  { title: "Guernsey", value: "GGY" },
  { title: "Ghana", value: "GHA" },
  { title: "Gibraltar", value: "GIB" },
  { title: "Guinea", value: "GIN" },
  { title: "Guadeloupe", value: "GLP" },
  { title: "Republic of the Gambia", value: "GMB" },
  { title: "Guinea-Bissau", value: "GNB" },
  { title: "Equatorial Guinea", value: "GNQ" },
  { title: "Greece", value: "GRC" },
  { title: "Saint Kitts and Nevis", value: "KNA" },
  { title: "Republic of Korea", value: "KOR" },
  { title: "Kuwait", value: "KWT" },
  { title: "Lao People's Democratic Repub*", value: "LAO" },
  { title: "Liberia", value: "LBR" },
  { title: "Grenada", value: "GRD" },
  { title: "Greenland", value: "GRL" },
  { title: "Guatemala", value: "GTM" },
  { title: "French Guiana", value: "GUF" },
  { title: "Guam", value: "GUM" },
  { title: "Tuvalu", value: "TUV" },
  { title: "Republic Of China", value: "TWN" },
  { title: "Tanzania", value: "TZA" },
  { title: "Uganda", value: "UGA" },
  { title: "Ukraine", value: "UKR" },
  { title: "Uruguay", value: "URY" },
  { title: "United States", value: "USA" },
  { title: "Uzbekistan", value: "UZB" },
  { title: "Vatican City", value: "VAT" },
  { title: "Guyana", value: "GUY" },
  { title: "Honduras", value: "HND" },
  { title: "Croatia", value: "HRV" },
  { title: "Haiti", value: "HTI" },
  { title: "Hungary", value: "HUN" },
  { title: "Isle of Man", value: "IMN" },
  { title: "India", value: "IND" },
  { title: "Ireland", value: "IRL" },
  { title: "Islamic Republic of Iran", value: "IRN" },
  { title: "Republic of Iraq", value: "IRQ" },
  { title: "Iceland", value: "ISL" },
  { title: "Israel", value: "ISR" },
  { title: "Nord-Ovest", value: "ITA" },
  { title: "Jamaica", value: "JAM" },
  { title: "Niue", value: "NIU" },
  { title: "Kingdom of the Netherlands", value: "NLD" },
  { title: "Norway", value: "NOR" },
  { title: "NEPAL", value: "NPL" },
  { title: "Nauru", value: "NRU" },
  { title: "New Zealand", value: "NZL" },
  { title: "Oman", value: "OMN" },
  { title: "Pakistan", value: "PAK" },
  { title: "The Republic of Panama", value: "PAN" },
  { title: "Pitcairn Island", value: "PCN" },
  { title: "the Hashemite Kingdom of Jordan", value: "JOR" },
  { title: "Japan", value: "JPN" },
  { title: "Kazakhstan", value: "KAZ" },
  { title: "Republic of Kenya", value: "KEN" },
  { title: "Kyrgyzstan", value: "KGZ" },
  { title: "Cambodia", value: "KHM" },
  { title: "Kiribati", value: "KIR" },
  { title: "Peru", value: "PER" },
  { title: "The Philippines", value: "PHL" },
  { title: "Palau", value: "PLW" },
  { title: "Papua New Guinea", value: "PNG" },
  { title: "Poland", value: "POL" },
  { title: "Democratic Peoples Republic of Korea (the)", value: "PRK" },
  { title: "Portugal", value: "PRT" },
  { title: "Paraguay", value: "PRY" },
  { title: "State of Palestine", value: "PSE" },
  { title: "French Polynesia", value: "PYF" },
  { title: "Qatar", value: "QAT" },
  { title: "Libya", value: "LBY" },
  { title: "Saint Lucia", value: "LCA" },
  { title: "Liechtenstein", value: "LIE" },
  { title: "Sri Lanka", value: "LKA" },
  { title: "Lesotho", value: "LSO" },
  { title: "Lithuania", value: "LTU" },
  { title: "Luxembourg", value: "LUX" },
  { title: "the Republic of Latvia", value: "LVA" },
  { title: "Morocco", value: "MAR" },
  { title: "Monaco", value: "MCO" },
  { title: "Republic of Moldova", value: "MDA" },
  { title: "Madagascar", value: "MDG" },
  { title: "Maldives", value: "MDV" },
  { title: "Mexico", value: "MEX" },
  { title: "Marshall Islands", value: "MHL" },
  { title: "Republic of Macedonia", value: "MKD" },
  { title: "Mali", value: "MLI" },
  { title: "Malta", value: "MLT" },
  { title: "Myanmar", value: "MMR" },
  { title: "Montenegro", value: "MNE" },
  { title: "Mongolia", value: "MNG" },
  { title: "Eswatini", value: "SWZ" },
  { title: "Seychelles", value: "SYC" },
  { title: "Northern Mariana Islands", value: "MNP" },
  { title: "Mozambique", value: "MOZ" },
  { title: "Mauritania", value: "MRT" },
  { title: "Montserrat", value: "MSR" },
  { title: "Martinique", value: "MTQ" },
  { title: "Mauritius", value: "MUS" },
  { title: "Malawi", value: "MWI" },
  { title: "Malaysia", value: "MYS" },
  { title: "Syrian Arab Republic", value: "SYR" },
  { title: "Turks and Caicos", value: "TCA" },
  { title: "Chad", value: "TCD" },
  { title: "Togo", value: "TGO" },
  { title: "Thailand", value: "THA" },
  { title: "Tajikistan", value: "TJK" },
  { title: "Turkmenistan", value: "TKM" },
  { title: "Timor-Leste", value: "TLS" },
  { title: "Tonga", value: "TON" },
  { title: "Mayotte", value: "MYT" },
  { title: "Republic of Namibia", value: "NAM" },
  { title: "New Caledonia", value: "NCL" },
  { title: "Niger", value: "NER" },
  { title: "the Federal Republic of Nigeria", value: "NGA" },
  { title: "Nicaragua", value: "NIC" },
  { title: "R\u00c3\u00a9union", value: "REU" },
  { title: "Romania", value: "ROU" },
  { title: "Russian Federation", value: "RUS" },
  { title: "Rwanda", value: "RWA" },
  { title: "Saudi Arabia", value: "SAU" },
  { title: "Sudan", value: "SDN" },
  { title: "Senegal", value: "SEN" },
  { title: "Singapore", value: "SGP" },
  { title: "Saint Helena, Ascension, and Tristan da Cunha", value: "SHN" },
  { title: "Solomon Islands", value: "SLB" },
  { title: "Republic of Sierra Leone", value: "SLE" },
  { title: "El Salvador", value: "SLV" },
  { title: "San Marino", value: "SMR" },
  { title: "Somalia", value: "SOM" },
  { title: "Serbia", value: "SRB" },
  { title: "South Sudan", value: "SSD" },
  { title: "Sao Tome and Principe", value: "STP" },
  { title: "Suriname", value: "SUR" },
  { title: "Slovakia", value: "SVK" },
  { title: "Slovenia", value: "SVN" },
  { title: "Sweden", value: "SWE" },
  { title: "Trinidad and Tobago", value: "TTO" },
  { title: "Tunisia", value: "TUN" },
  { title: "Turkey", value: "TUR" },
  { title: "Virgin Islands", value: "VIR" },
  { title: "Vietnam", value: "VNM" },
  { title: "Vanuatu", value: "VUT" },
  { title: "Wallis and Futuna", value: "WLF" },
  { title: "Samoa", value: "WSM" },
  { title: "Kosovo", value: "XKX" },
  { title: "Yemen", value: "YEM" },
  { title: "South Africa", value: "ZAF" },
  { title: "Zambia", value: "ZMB" },
  { title: "Zimbabwe", value: "ZWE" },
  { title: "Saint Vincent and the Grenadines", value: "VCT" },
  { title: "Bolivarian Republic of Venezuela", value: "VEN" },
  { title: "British Virgin Islands", value: "VGB" },
  { title: "Tokelau", value: "TKL" },
];
