version = 0.1
[default.deploy.parameters]
stack_name = "borders-app"
resolve_s3 = true
s3_prefix = "borders-app"
region = "eu-central-1"
confirm_changeset = false
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
image_repositories = []
