AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  auth-resources

  SAM Template for auth resources

Resources:
  CloudFront:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./webapp/template.yaml
  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./api/template.yaml
